/**
 * Primary package containing controller classes.
 * <p>
 *     Generated by IntelliJ IDEA, this package contains all necessary controllers for the
 *     implementation of the Restaurant Inventory Management System. -> Continue...
 * </p>
 */
package mp.ims.mpgroup4;